language: php

sudo: false

env:
    - COMPOSER_OPTIONS="

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env:
        - COMPOSER_OPTIONS="--prefer-stable"
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer update -n "$COMPOSER_OPTIONS"

script:
    - vendor/bin/simple-phpunit
