language: php

sudo: false

env:
    - COMPOSER_OPTIONS="

matrix:
  include:
    - php: 7.1
      env:
	  - COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.1
      env:
	  - COMPOSER_OPTIONS="--prefer-stable"
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer update -n "$COMPOSER_OPTIONS"

script:
    - vendor/bin/phpunit
